### ISSUE TITLE
Add LLVM toolchain support for cryptsetup module

### ISSUE THREAD

**Issue by elde-n** [desultory/ugrd#13]

**Comment by desultory** [comment]
Do you have an error message? That module has to pull the libc module, and currently has glibc support. I don't currently have any systems with LLVM to test on.

https://github.com/desultory/ugrd/blob/main/src/ugrd/crypto/cryptsetup.py#L288 this is where it currently looks for libgcc_s.

If you can determine the libraries required with llvm, that would help to add support.

**Comment by elde-n** [comment]
because I'm on musl the error itself is
```
$ ldconfig -p
Unimplemented option: -p
```

and iirc 'libgcc_s.so' is just llvm's libunwind (/lib/libunwind.so)

**Comment by desultory** [comment]
If you add this to your main config, it will stop that from running. 

```masks.build_pre = [ "find_libgcc" ]``` 

Maybe it will just work? It's worth a try. If cryptsetup runs but fails to decrypt, it's likely from missing libraries. That function is added as a hack to make gcc compiled stuff work because it doesn't list that library in lddtree even though it's needed.

**Comment by desultory** [comment]
> because I'm on musl the error itself is
> 
> ```
> $ ldconfig -p
> Unimplemented option: -p
> ```
> 
> and iirc 'libgcc_s.so' is just llvm's libunwind (/lib/libunwind.so)

you're also free to manually add that to `dependencies` where it will copy it with the same destination and resolve/create symlinks or `copies` where you can manually specify a source file and destination within the initramfs.

**Comment by desultory** [comment]
the latest version in the repo should work, it will log a critical error and you can disable it searching for that file with `find_libgcc = false`

**Comment by elde-n** [comment]
thanks

**Comment by desultory** [comment]
> thanks

you're welcome, were you able to test this?

**Comment by elde-n** [comment]
Sorry for the late response, yes it works better than dracut (much better)
