### ISSUE TITLE
ugrd not finding libargon2.so

### ISSUE THREAD

**Issue by Proto1337** [desultory/ugrd#140]
Hi,

with ugrd >1.22.0 I am unable to build an initramfs due to it failing for not finding `libargon2.so` despite it being installed. Versions <= 1.22.0 work flawlessly.

I execute ugrd like this to generate my initramfs:  
`sudo ugrd --no-compress --firmware --hostonly --lspci --lsmod --kver 6.12.6-gentoo-proto /tmp/initramfs.cpio`

Maybe this helps: I also attached the output from `ugrd --no-log-color --log-file out.log -d`.  
Also for more context: I am on Gentoo (btw) and have this profile set currently "default/linux/amd64/23.0/no-multilib/hardened".  
The path to `libargon2.so` on my system is `/usr/lib64/libargon2.so` which then symlinks to `/usr/lib64/libargon2.so.1`.

[out.log](https://github.com/user-attachments/files/18219151/out.log)

Thanks for the great work! <3

**Comment by desultory** [comment]
Can you share the output of `equery b /usr/lib64/libargon2.so` , `lddtree $(which cryptsetup)`  and `openssl list -kdf-algorithms` please?

Equery is in gentoolkit it you do not have it. 

What version are you on, have you tried the latest git sources?

This argon check was added around 1.22, and was originally a bit too strict. Later versions are more relaxed. I'm not entirely sure why, but sometimes cryptsetup is linked again libargon, other times it's linked against libcrypto (openssl). Later versions check if openssl is linked and has argon support, but the original check did not. You can see how it works here: https://github.com/desultory/ugrd/blob/main/src/ugrd/crypto/cryptsetup.py#L287-L299

As a side note, the `hostonly` option is enabled by default. `lsmod` detection may not be needed any more as now mounts attempt to detect required kmods based on the device type as well.

**Comment by Proto1337** [comment]
Sure.

[equery.txt](https://github.com/user-attachments/files/18219336/equery.txt)
[lddtree.txt](https://github.com/user-attachments/files/18219337/lddtree.txt)
[openssl.txt](https://github.com/user-attachments/files/18219338/openssl.txt)

I am currently on v1.28.2.  
I also just unmasked 9999 and tried it. I still have the same issue.

Checking what cryptsetup is linking to, I just remembered that I changed my USE-flags for cryptsetup when I was testing stuff. I had `-openssl` and `gcrypt` set; now I changed it back to use OpenSSL again and the issue is gone. Now everything works normal.

Is this intended behavior that `openssl` for `sys-fs/cryptsetup` is needed?

**Comment by desultory** [comment]
> Sure.
> 
> [equery.txt](https://github.com/user-attachments/files/18219336/equery.txt) [lddtree.txt](https://github.com/user-attachments/files/18219337/lddtree.txt) [openssl.txt](https://github.com/user-attachments/files/18219338/openssl.txt)
> 
> I am currently on v1.28.2. I also just unmasked 9999 and tried it. I still have the same issue.
> 
> Checking what cryptsetup is linking to, I just remembered that I changed my USE-flags for cryptsetup when I was testing stuff. I had `-openssl` and `gcrypt` set; now I changed it back to use OpenSSL again and the issue is gone. Now everything works normal.
> 
> Is this intended behavior that `openssl` for `sys-fs/cryptsetup` is needed?

Not necessarily, that's just all it's been tested on. I'll look into adding gcrypt support, thanks for sharing that detail.

**Comment by desultory** [comment]
It seems that removing the argon2 USE flag forces cryptsetup to build PBKDF2 support.

Can you check the output of `cryptsetup --help` to see if it says you have argon2 support when ugrd says you do not? the check may be working as intended, but the ebuild may have issues.

It seems argon2 support from gcrypt is not considered, so it forced PBKDF2 when libargon2 is not specifically used.

**Comment by Proto1337** [comment]
> Can you check the output of cryptsetup --help to see if it says you have argon2 support when ugrd says you do not? the check may be working as intended, but the ebuild may have issues.

I get this output from `cryptsetup --help`:
```
Default PBKDF for LUKS2: argon2id
	Iteration time: 2000, Memory required: 1048576kB, Parallel threads: 4
```

I had `cryptsetup` built with these USE-flags:
```
sys-fs/cryptsetup-2.7.5::gentoo was built with the following:
USE="argon2 gcrypt nls udev urandom -fips -kernel -nettle -openssl -pwquality -ssh -static -static-libs -test"
```

**Comment by desultory** [comment]
> > Can you check the output of cryptsetup --help to see if it says you have argon2 support when ugrd says you do not? the check may be working as intended, but the ebuild may have issues.
> 
> I get this output from `cryptsetup --help`:
> 
> ```
> Default PBKDF for LUKS2: argon2id
> 	Iteration time: 2000, Memory required: 1048576kB, Parallel threads: 4
> ```
> 
> I had `cryptsetup` built with these USE-flags:
> 
> ```
> sys-fs/cryptsetup-2.7.5::gentoo was built with the following:
> USE="argon2 gcrypt nls udev urandom -fips -kernel -nettle -openssl -pwquality -ssh -static -static-libs -test"
> ```

Does it still say it supports argon2id when you use -argon2?

**Comment by Proto1337** [comment]
With `-argon2` it does not say anymore that Argon2 is supported. Now it returns:
```
Default PBKDF for LUKS2: pbkdf2
	Iteration time: 2000, Memory required: 0kB, Parallel threads: 0
```

Current USE-flags:
```
sys-fs/cryptsetup-2.7.5::gentoo was built with the following:
USE="gcrypt nls udev urandom -argon2 -fips -kernel -nettle -openssl -pwquality -ssh -static -static-libs -test"
```

**Comment by desultory** [comment]
> With `-argon2` it does not say anymore that Argon2 is supported. Now it returns:
> 
> ```
> Default PBKDF for LUKS2: pbkdf2
> 	Iteration time: 2000, Memory required: 0kB, Parallel threads: 0
> ```
> 
> Current USE-flags:
> 
> ```
> sys-fs/cryptsetup-2.7.5::gentoo was built with the following:
> USE="gcrypt nls udev urandom -argon2 -fips -kernel -nettle -openssl -pwquality -ssh -static -static-libs -test"
> ```

OK, I think this confirms that the ugrd check was functioning properly by chance. I'm still looking for a way to check if it has gcrypt argon support by checking gcrypt capabilities. I may just make it check the output from cryptsetup -help, as whatever it lists as the default should work.

It seems that removing the argon2 USE flag means it doesn't use the gcrypt argon2 support. Interestingly, adding the argon2 use flag with gcrypt builds argon2 support linked with gcrypt and not argon2, despite what the USE flag info suggests.

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/pull/142

Can you let me know if this helps? The "default" listed in --help isn't necessarily all it supports. Now it checks what cryptsetup reports as its backend, and tries to check if that backend support argon2.

**Comment by Proto1337** [comment]
Yes, I just tried it and it works now. Thanks!

**Comment by desultory** [comment]
> Yes, I just tried it and it works now. Thanks!

Thanks for testing, I appreciate the feedback.
