### ISSUE TITLE
Plain LVM in chroot, results in key error trying to generate initramfs

### ISSUE THREAD

**Issue by samip5** [desultory/ugrd#66]
Paste can be seen here: https://bpa.st/3MMIS
Version 1.19.4

```
ERROR    | 'sda2'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ugrd/main.py", line 60, in main
    generator.build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 78, in build
    self.run_hook(hook)
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 120, in run_hook
    if function_output := self.run_func(function, *args, **kwargs):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 89, in run_func
    if function_output := function(self):
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 352, in autodetect_root_dm
    _autodetect_dm(self, '/')
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 344, in _autodetect_dm
    return autodetect_root_lvm(self, source_device, dm_num, dm_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 371, in autodetect_root_lvm
    _autodetect_dm(self, '/dev/' + slave)
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 31, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 305, in _autodetect_dm
    source_device = "/dev/mapper/" + self['_dm_info'][mountpoint.split('/')[-1]]['name']
                                     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sda2'
```

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/mounts.py#L302

Can you share your `_mounts` config section? (printed in the output on exception)

It didn't find /dev/sda2 on `_mounts` so it looked for that name as a mapped device. It should be reading /proc/mounts to get mount info, so maybe that wasn't passed to the chroot properly?

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/mounts.py#L371

Ah I think the issue is here, it kinda assumes you're using LVM under LUKS, making this accept failures should fix it, thanks for finding this

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/commit/0e4d2d6b784d667bf3162939b42436f9073f4b7a I think this should work, im about to run some tests, I don't have any vms that are plain lvm right now

**Comment by desultory** [comment]
Works in my test vm, please let me know if it doesn't work for you.

**Comment by samip5** [comment]
It does indeed work, like I said on IRC. :)

**Comment by madsl** [comment]
@desultory sorry for asking in an issue report - I guess it would be the easiest in IRC, but I have no idea where you can be contacted.

As mentioned [here](https://github.com/systemd/systemd/issues/33920#issuecomment-2337760685), I also ran into the issue where systemd stalls waiting for a btrfs device opened through cryptsetup in a custom initrd, and your trick from [fakeudev.py](https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/fakeudev.py) seems like it should do wonders. But I can't seem to understand how it is ment to be used.

If I in the initrd mount a tmpfs on /run with the same options as systemd does (and populate it with /run/udev/data/b254:0 with your script), that script output disappears after switching root to /newroot with systemd. I've tried both moving the mount to newroot and not when switching root, but it seems like the tmpfs is just wiped or reset (or something like it) when entering systemd. I can not find "DM_UDEV_PRIMARY_SOURCE_FLAG" anywhere in /run/udev/data after systemd has booted.

Do I have to do anything else after creating /run/udev/data/b254:0 with the script to make the new udev use it/not erase it, or is there anything else I'm forgetting...?

**Comment by madsl** [comment]
I actually found out I could do it in another hacky way, by doing this:

```
$ cat /etc/udev/rules.d/99-zoverride.rules
SUBSYSTEM=="block", KERNEL=="dm-0", ENV{SYSTEMD_READY}="1"
```
The rules must be read after 99-systemd.rules, hence the filename.

But it would be nice to know how a udev-less initrd can solve this too...

**Comment by desultory** [comment]
> @desultory sorry for asking in an issue report - I guess it would be the easiest in IRC, but I have no idea where you can be contacted.
> 

Is this related to using LVM on a systemd system?

> As mentioned [here](https://github.com/systemd/systemd/issues/33920#issuecomment-2337760685), I also ran into the issue where systemd stalls waiting for a btrfs device opened through cryptsetup in a custom initrd, and your trick from [fakeudev.py](https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/fakeudev.py) seems like it should do wonders. But I can't seem to understand how it is ment to be used.
> 

To use this module, you simply need to load it. You can add `ugrd.fs.fakeudev` to your `modules` definition in the config.toml.

I'm considering making it autodetect it, but the LVM/Systemd dev suggest this is somehow unsafe and I'd like to test more before I do something like that.

> If I in the initrd mount a tmpfs on /run with the same options as systemd does (and populate it with /run/udev/data/b254:0 with your script), that script output disappears after switching root to /newroot with systemd. I've tried both moving the mount to newroot and not when switching root, but it seems like the tmpfs is just wiped or reset (or something like it) when entering systemd. I can not find "DM_UDEV_PRIMARY_SOURCE_FLAG" anywhere in /run/udev/data after systemd has booted.
> 
> Do I have to do anything else after creating /run/udev/data/b254:0 with the script to make the new udev use it/not erase it, or is there anything else I'm forgetting...?

/run should be carried into the switch_root target. If using the `fakeudev` module it should automatically handle all of this.

**Comment by desultory** [comment]
> I actually found out I could do it in another hacky way, by doing this:
> 
> ```
> $ cat /etc/udev/rules.d/99-zoverride.rules
> SUBSYSTEM=="block", KERNEL=="dm-0", ENV{SYSTEMD_READY}="1"
> ```
> 
> The rules must be read after 99-systemd.rules, hence the filename.
> 
> But it would be nice to know how a udev-less initrd can solve this too...

so you put this on the host? 

TBH this hack is _only_ needed so systemd is able to see a mount as being present when it is. I think ideally that is signaled before it does switch_root, so the host doesn't need adjustment.

**Comment by madsl** [comment]
Yep
