### ISSUE TITLE
is it possible to use a different keyboard layout?

### ISSUE THREAD

**Issue by mrlogick** [desultory/ugrd#9]
When asked for the password to decrypt the luks partition I have to use the US layout (in my case with an italian keyboard).
Is it possible to use a different layout?
Is this ugrd related, or I need to configure the layout somewhere else?

**Comment by desultory** [comment]
> When asked for the password to decrypt the luks partition I have to use the US layout (in my case with an italian keyboard). Is it possible to use a different layout? Is this ugrd related, or I need to configure the layout somewhere else?

This should be possible, I don't have any keyboards to test with, but assuming the proper keymap is provided, I don't see why it wouldn't work.

I think `loadkeys` may be the best choice here. It shouldn't be too hard to make a module for this, it just needs a binary defintion for that file and then a config option that adds a that file as a dependency, then a init hook that loads that keymap.

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/commit/e6239e40b0159a85a0ac615cdb8d36c58a4d7ade

Please let me know if this works, you should just have to specify the keymap file. I haven't tested this, but may have time later.

**Comment by desultory** [comment]
That commit was incomplete, I've tested basic support and it'll be in release1.0.0
